# Form implementation generated from reading ui file 'mainwindow_rework.ui'
# Created by: PyQt5 UI code generator 5.14.1
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(693, 553)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ui_central_graphics_area_graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.ui_central_graphics_area_graphicsView.setEnabled(True)
        self.ui_central_graphics_area_graphicsView.setObjectName("ui_central_graphics_area_graphicsView")
        self.gridLayout_2.addWidget(self.ui_central_graphics_area_graphicsView, 2, 0, 1, 7)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ui_difficulty_easy_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.ui_difficulty_easy_pushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ui_difficulty_easy_pushButton.setObjectName("ui_difficulty_easy_pushButton")
        self.verticalLayout.addWidget(self.ui_difficulty_easy_pushButton)
        self.ui_difficulty_medium_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.ui_difficulty_medium_pushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ui_difficulty_medium_pushButton.setObjectName("ui_difficulty_medium_pushButton")
        self.verticalLayout.addWidget(self.ui_difficulty_medium_pushButton)
        self.ui_difficulty_hard_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.ui_difficulty_hard_pushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ui_difficulty_hard_pushButton.setObjectName("ui_difficulty_hard_pushButton")
        self.verticalLayout.addWidget(self.ui_difficulty_hard_pushButton)
        self.gridLayout_2.addLayout(self.verticalLayout, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 4, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 0, 0, -1)
        self.gridLayout.setHorizontalSpacing(70)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ui_skip_to_start_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.ui_skip_to_start_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.ui_skip_to_start_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/skip_to_begin.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ui_skip_to_start_pushButton.setIcon(icon)
        self.ui_skip_to_start_pushButton.setIconSize(QtCore.QSize(100, 42))
        self.ui_skip_to_start_pushButton.setObjectName("ui_skip_to_start_pushButton")
        self.horizontalLayout.addWidget(self.ui_skip_to_start_pushButton)
        self.ui_skip_back_one_step_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_skip_back_one_step_pushButton.sizePolicy().hasHeightForWidth())
        self.ui_skip_back_one_step_pushButton.setSizePolicy(sizePolicy)
        self.ui_skip_back_one_step_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.ui_skip_back_one_step_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/step_backwards.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ui_skip_back_one_step_pushButton.setIcon(icon1)
        self.ui_skip_back_one_step_pushButton.setIconSize(QtCore.QSize(100, 25))
        self.ui_skip_back_one_step_pushButton.setObjectName("ui_skip_back_one_step_pushButton")
        self.horizontalLayout.addWidget(self.ui_skip_back_one_step_pushButton)
        self.ui_skip_forward_one_step_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.ui_skip_forward_one_step_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.ui_skip_forward_one_step_pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/step_forwards.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ui_skip_forward_one_step_pushButton.setIcon(icon2)
        self.ui_skip_forward_one_step_pushButton.setIconSize(QtCore.QSize(100, 25))
        self.ui_skip_forward_one_step_pushButton.setObjectName("ui_skip_forward_one_step_pushButton")
        self.horizontalLayout.addWidget(self.ui_skip_forward_one_step_pushButton)
        self.ui_skip_to_end_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.ui_skip_to_end_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.ui_skip_to_end_pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/skip_to_end.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ui_skip_to_end_pushButton.setIcon(icon3)
        self.ui_skip_to_end_pushButton.setIconSize(QtCore.QSize(100, 42))
        self.ui_skip_to_end_pushButton.setObjectName("ui_skip_to_end_pushButton")
        self.horizontalLayout.addWidget(self.ui_skip_to_end_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.ui_take_string_to_test_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_take_string_to_test_lineedit.sizePolicy().hasHeightForWidth())
        self.ui_take_string_to_test_lineedit.setSizePolicy(sizePolicy)
        self.ui_take_string_to_test_lineedit.setMinimumSize(QtCore.QSize(200, 30))
        self.ui_take_string_to_test_lineedit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ui_take_string_to_test_lineedit.setObjectName("ui_take_string_to_test_lineedit")
        self.verticalLayout_3.addWidget(self.ui_take_string_to_test_lineedit)
        self.ui_input_accepted_or_rejected_label = QtWidgets.QLabel(self.centralwidget)
        self.ui_input_accepted_or_rejected_label.setObjectName("ui_input_accepted_or_rejected_label")
        self.verticalLayout_3.addWidget(self.ui_input_accepted_or_rejected_label)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 2, 1, 1)
        self.ui_live_input_proc_summary_label = QtWidgets.QLabel(self.centralwidget)
        self.ui_live_input_proc_summary_label.setObjectName("ui_live_input_proc_summary_label")
        self.gridLayout_2.addWidget(self.ui_live_input_proc_summary_label, 3, 3, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ui_request_hint_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_request_hint_pushButton.sizePolicy().hasHeightForWidth())
        self.ui_request_hint_pushButton.setSizePolicy(sizePolicy)
        self.ui_request_hint_pushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ui_request_hint_pushButton.setObjectName("ui_request_hint_pushButton")
        self.verticalLayout_2.addWidget(self.ui_request_hint_pushButton)
        self.ui_submit_solution_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.ui_submit_solution_pushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ui_submit_solution_pushButton.setObjectName("ui_submit_solution_pushButton")
        self.verticalLayout_2.addWidget(self.ui_submit_solution_pushButton)
        self.ui_toggle_solution_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.ui_toggle_solution_pushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ui_toggle_solution_pushButton.setObjectName("ui_toggle_solution_pushButton")
        self.verticalLayout_2.addWidget(self.ui_toggle_solution_pushButton)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 3, 6, 1, 1)
        self.ui_problem_to_solve_tooltip_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_problem_to_solve_tooltip_label.sizePolicy().hasHeightForWidth())
        self.ui_problem_to_solve_tooltip_label.setSizePolicy(sizePolicy)

        self.ui_problem_to_solve_tooltip_label.setBaseSize(QtCore.QSize(3, 0))
        self.ui_problem_to_solve_tooltip_label.setLineWidth(3)
        self.ui_problem_to_solve_tooltip_label.setMidLineWidth(3)
        self.ui_problem_to_solve_tooltip_label.setObjectName("ui_problem_to_solve_tooltip_label")
        self.gridLayout_2.addWidget(self.ui_problem_to_solve_tooltip_label, 1, 0, 1, 7)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ui_difficulty_easy_pushButton.setText(_translate("MainWindow", "Easy"))
        self.ui_difficulty_medium_pushButton.setText(_translate("MainWindow", "Medium"))
        self.ui_difficulty_hard_pushButton.setText(_translate("MainWindow", "Hard"))
        self.ui_input_accepted_or_rejected_label.setText(_translate("MainWindow", "TK: accepted or rejected"))
        self.ui_live_input_proc_summary_label.setText(_translate("MainWindow", "TK: live summary"))
        self.ui_request_hint_pushButton.setText(_translate("MainWindow", "Hint"))
        self.ui_submit_solution_pushButton.setText(_translate("MainWindow", "Submit"))
        self.ui_toggle_solution_pushButton.setText(_translate("MainWindow", "Toggle solution"))
        self.ui_problem_to_solve_tooltip_label.setText(_translate("MainWindow", "Problem to solve:  "))
import resources.resources_rc